
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import FeaturesBar from '@/components/features/features';
import NewsletterBar from '@/components/newsletter/newsletter';
import Footer from '@/components/footer/footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>
				<Navbar />
				<main>
					{children}
				</main>
				<footer>
					<FeaturesBar />
					<NewsletterBar />
					<Footer />
				</footer>
			</body>
		</html>
	)
}
